    '''
    #primeiros conceitos
    g.add_vertex('a')
    g.add_vertex('b')
    g.add_vertex('c')
    g.add_vertex('d')
    g.add_vertex('e')
    g.add_vertex('f')
    g.add_vertex('g')
    g.add_vertex('h')
    g.add_vertex('i')
    g.add_vertex('j')

    g.add_edge('a', 'c', 60)  
    g.add_edge('c', 'e', 70)
    g.add_edge('e', 'g', 70)
    g.add_edge('g', 'i', 80)
    g.add_edge('b', 'a', 170)
    g.add_edge('c', 'd', 180)
    g.add_edge('f', 'e', 180)
    g.add_edge('g', 'h', 180)
    g.add_edge('j', 'i', 190)
    g.add_edge('b', 'd', 70)
    g.add_edge('d', 'b', 70)
    g.add_edge('d', 'f', 70)
    g.add_edge('f', 'd', 70)
    g.add_edge('f', 'h', 70)
    g.add_edge('h', 'f', 70)
    g.add_edge('h', 'j', 70)
    g.add_edge('j', 'h', 70) 
    '''
    '''
    #dfs?
    g.add_vertex('1')
    g.add_vertex('2')
    g.add_vertex('3')
    g.add_vertex('4')
    g.add_vertex('5')
    g.add_vertex('6')

    g.add_edge('1','2',1)
    g.add_edge('1','3',2)
    g.add_edge('2','1',3)
    g.add_edge('2','4',4)
    g.add_edge('2','5',5)
    g.add_edge('3','1',6)
    g.add_edge('3','5',7)
    g.add_edge('4','2',8)
    g.add_edge('4','5',9)
    g.add_edge('4','6',10)
    g.add_edge('5','2',11)
    g.add_edge('5','3',12)
    g.add_edge('5','4',13)
    g.add_edge('5','6',14)
    g.add_edge('6','4',15)
    g.add_edge('6','5',16)
    '''

    '''
    #dfs?
    g.add_vertex('0')
    g.add_vertex('1')
    g.add_vertex('2')
    g.add_vertex('3')

    g.add_edge('0','1',1)
    g.add_edge('0','2',1)
    g.add_edge('1','2',1)
    g.add_edge('2','0',1)
    g.add_edge('2','3',1)
    g.add_edge('3','3',1)
    '''

    '''
    #prova1
    g.add_vertex('e')
    g.add_vertex('1')
    g.add_vertex('2')
    g.add_vertex('3')
    g.add_vertex('4')
    g.add_vertex('5')
    g.add_vertex('6')
    g.add_vertex('7')
    g.add_vertex('8')
    g.add_vertex('9')
    g.add_vertex('10')
    g.add_vertex('11')
    g.add_vertex('12')
    g.add_vertex('13')
    g.add_vertex('14')
    g.add_vertex('15')
    g.add_vertex('16')
    g.add_vertex('17')
    g.add_vertex('18')
    g.add_vertex('s')

    g.add_edge('e', '0', 0)
    g.add_edge('e', '1', 0)
    g.add_edge('0', '1', 0)
    g.add_edge('1', '2', 0)
    g.add_edge('2', '3', 0)
    g.add_edge('3', '4', 0)
    g.add_edge('3', '14', 0)
    g.add_edge('4', '5', 0)
    g.add_edge('4', '7', 0)
    g.add_edge('5', '6', 0)
    g.add_edge('5', '8', 0)
    g.add_edge('8', '9', 0)
    g.add_edge('8', '10', 0)
    g.add_edge('10', '11', 0)
    g.add_edge('10', '12', 0)
    g.add_edge('10', '13', 0)
    g.add_edge('14', '15', 0)
    g.add_edge('15', 's', 0)
    g.add_edge('15', '16', 0)
    g.add_edge('16', '17', 0)
    g.add_edge('16', '18', 0)
    g.add_edge('s', '16', 0)
    '''

    '''
    #dijkstra
    g.add_vertex('s')
    g.add_vertex('v')
    g.add_vertex('w')
    g.add_vertex('t')

    g.add_edge('s', 'v', 1)
    g.add_edge('s', 'w', 4)
    g.add_edge('v', 'w', 2)
    g.add_edge('v', 't', 6)
    g.add_edge('w', 't', 3)
    '''

    '''
    #reuniao
    g.add_vertex('0')
    g.add_vertex('1')
    g.add_vertex('2')
    g.add_vertex('3')
    g.add_vertex('4')
    g.add_vertex('5')
    g.add_vertex('6')
  
    g.add_edge('0', '1', 22)
    g.add_edge('0', '2', 30)
    g.add_edge('0', '5', 55)
    g.add_edge('1', '5', 11)
    g.add_edge('1', '6', 30)
    g.add_edge('1', '2', 25)
    g.add_edge('2', '3', 15)
    g.add_edge('2', '6', 10)
    g.add_edge('3', '4', 15)
    g.add_edge('3', '5', 10)
    g.add_edge('4', '5', 20)
    g.add_edge('5', '6', 33)
    '''
    '''
    #bellman-Ford
    g.add_vertex('a')
    g.add_vertex('b')
    g.add_vertex('c')
    g.add_vertex('d')
    g.add_vertex('e')

    g.add_edge('a', 'b', -1)
    g.add_edge('a', 'c', 4)
    g.add_edge('b', 'c', 3)
    g.add_edge('b', 'd', 2)
    g.add_edge('b', 'e', 2)
    g.add_edge('d', 'c', 5)
    g.add_edge('d', 'b', 1)
    g.add_edge('e', 'd', -3)
    '''

    '''
    #floydWarshall
    g.add_vertex('1')
    g.add_vertex('2')
    g.add_vertex('3')
    g.add_vertex('4')

    g.add_edge('1', '2', 3)
    g.add_edge('1', '4', 2)
    g.add_edge('2', '1', 8)
    g.add_edge('2', '3', 2)
    g.add_edge('3', '1', 5)
    g.add_edge('3', '4', 1)
    g.add_edge('4', '1', 7)

    g.add_vertex('0')
    g.add_vertex('1')
    g.add_vertex('2')
    g.add_vertex('3')

    g.add_edge('0', '3', 10)
    g.add_edge('0', '1', 5)
    g.add_edge('1', '2', 3)
    g.add_edge('2', '3', 1)
    '''